# Dependencies
markdown        : kramdown
highlighter     : rouge

# Permalinks
permalink       : pretty

# Setup
title           : 'Path Sticker'
tagline         : 'Just another HackTools'
description     : 'This is my personal website where I post about projects, ideas and general tech stuff'
url             : /
baseurl         : /

author      :
  name          : 'darkbite'
  url           : https://harimurti.net

gems            : [jekyll-paginate]
paginate        : 5

website     :
  github        : https://github.com/pathsticker
